// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBlmN9pyDr-V-wUph2HZADvGr7P--wdcg',
    appId: '1:82662468366:android:ea4ae103ad89756891055f',
    messagingSenderId: '82662468366',
    projectId: 'rozrides-v2',
    storageBucket: 'rozrides-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbEYb5Z3PL6DpHqUAclRv8f4PmUD_QpPw',
    appId: '1:82662468366:ios:16fd0d9c8b3b0c9091055f',
    messagingSenderId: '82662468366',
    projectId: 'rozrides-v2',
    storageBucket: 'rozrides-v2.firebasestorage.app',
    iosBundleId: 'com.example.rozrides',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUx6soVEBrec21d_2hooM8vi120q5Mymc',
    appId: '1:82662468366:web:ac61837fb345621f91055f',
    messagingSenderId: '82662468366',
    projectId: 'rozrides-v2',
    authDomain: 'rozrides-v2.firebaseapp.com',
    storageBucket: 'rozrides-v2.firebasestorage.app',
    measurementId: 'G-EJ71XWV787',
  );

}